In [85]:
import h5py
import numpy as np
import sys, os

In [47]:
a = np.ones((15,15))
for i in range(15):
    a[i,:] = a[i,:]*i

In [76]:
f = h5py.File('test_file.h5','w')

In [77]:
f.create_dataset('data', (15,15),dtype='float64',data=a,chunks=(1,15))

<HDF5 dataset "data": shape (15, 15), type "<f8">

In [78]:
f.close()

In [107]:
def opener(path,flags):
    flag_list = [flags, os.O_DIRECT]
    return os.open(path, flags)

fd = open('test_file.h5', 'rb', opener=opener)
f = h5py.File(fd, 'r')

In [ ]:
# fd = open('test_file.h5', 'rb')
# f = h5py.File(fd, 'r')

In [80]:
print(np.array(f['data']))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
 [ 7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.  7.]
 [ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]
 [ 9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.  9.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [13. 13. 13. 13. 13. 13. 13. 13. 13. 13. 13. 13. 13. 13. 13.]
 [14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14. 14.]]


In [55]:
map = np.memmap('test_file.h5', mode="r", shape=f['data'].shape,
                                            offset=f['data'].id.get_offset(), dtype=f['data'].dtype)

In [56]:
map.strides

(120, 8)

In [82]:
id = f['data'].id

In [84]:
id.get_chunk_info(1)

AttributeError: 'h5py.h5d.DatasetID' object has no attribute 'get_chunk_info'