In [1]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import math
import h5py
import torch
from matplotlib.colors import LogNorm
import pandas as pd

# Add the path to the parent directory to augment search for module
par_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
if par_dir not in sys.path:
    sys.path.append(par_dir)
    
# Import the custom plotting module
from plot_utils import plot_utils

In [5]:
from torch.utils.data import DataLoader
from torch.utils.data.sampler import SubsetRandomSampler


import os
import time
import numpy as np

from io_utils.data_handling import WCH5Dataset 
from io_utils.custom_samplers import SubsetSequenceSampler

In [6]:
dset=WCH5Dataset("/fast_scratch/WatChMaL/data/IWCDmPMT/varyE/IWCDmPMT_varyE_100-1000MeV_300k_fmt.h5",
                 0.1,
                 0.1,
                 True,
                 None)

In [7]:
len(dset.train_indices)

720000

In [8]:
is_sorted = lambda a: np.all(a[:-1] <= a[1:])

In [9]:
is_sorted(dset.train_indices)

False

In [13]:
train_iter=DataLoader(dset, batch_size=32,shuffle=False,
                      sampler=SubsetRandomSampler(dset.train_indices))

In [14]:
train_iter_seq=DataLoader(dset, batch_size=32,shuffle=False,
                      sampler=SubsetSequenceSampler(dset.train_indices))

In [12]:
len(train_iter)

22500

In [15]:
len(train_iter_seq)

22500

In [16]:
len(dset)

900000

In [17]:
float(len(dset.train_indices)/float(32))

22500.0

In [26]:
epoch_indices=np.zeros((10,22500,32),dtype=int)
epoch_indices_seq=np.zeros((10,22500,32),dtype=int)

In [27]:
for epoch in range(10):
    for i, data in enumerate(train_iter):
        epoch_indices[epoch,i]=data[2]
        if i%1000==0:
            print("i: {}".format(i))

i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i

In [28]:
for epoch in range(10):
    for i, data in enumerate(train_iter_seq):
        epoch_indices_seq[epoch,i]=data[2]
        if i%1000==0:
            print("i: {}".format(i))

i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i: 4000
i: 5000
i: 6000
i: 7000
i: 8000
i: 9000
i: 10000
i: 11000
i: 12000
i: 13000
i: 14000
i: 15000
i: 16000
i: 17000
i: 18000
i: 19000
i: 20000
i: 21000
i: 22000
i: 0
i: 1000
i: 2000
i: 3000
i

In [22]:
np.sort(epoch_indices[0,0])

array([ 42693,  49641,  58699,  62783,  65777, 133891, 145476, 147652,
       155759, 169823, 204506, 208352, 210326, 293126, 295029, 319644,
       347704, 438152, 469301, 486692, 495630, 529106, 548534, 578777,
       619618, 665402, 705494, 772775, 789346, 795518, 855416, 891887])

In [23]:
np.sort(epoch_indices[1,0])

array([ 22852,  24132,  43912,  60131,  76692, 132713, 137847, 233772,
       269337, 276822, 322953, 338469, 394125, 402554, 432224, 522354,
       546832, 547204, 598343, 620938, 628466, 634311, 653358, 681318,
       714093, 735084, 738822, 740057, 743838, 847537, 883659, 895315])

In [24]:
np.sort(epoch_indices_seq[0,0])

array([ 13123,  50394,  73140, 119159, 161123, 166977, 193788, 234835,
       235258, 282983, 323109, 349703, 354015, 402846, 431481, 440374,
       484013, 484217, 527984, 555953, 570518, 618093, 619021, 682866,
       708347, 718642, 723638, 735813, 739834, 755792, 838022, 840870])

In [25]:
np.sort(epoch_indices_seq[1,0])

array([ 13123,  50394,  73140, 119159, 161123, 166977, 193788, 234835,
       235258, 282983, 323109, 349703, 354015, 402846, 431481, 440374,
       484013, 484217, 527984, 555953, 570518, 618093, 619021, 682866,
       708347, 718642, 723638, 735813, 739834, 755792, 838022, 840870])

In [29]:
59298 in dset.train_indices

True

In [30]:
epoch_indices.shape[1]

22500

In [31]:
indices_b=np.sort(epoch_indices)

In [32]:
indices_b=indices_b.reshape(-1,indices_b.shape[-1])

In [33]:
indices_b

array([[ 24942, 183749, 191654, ..., 863796, 877826, 879274],
       [ 81050, 160419, 189384, ..., 836388, 841550, 862722],
       [ 11728,  22436,  91144, ..., 755518, 812269, 836787],
       ...,
       [  3392,  18301,  42848, ..., 810252, 819047, 846349],
       [ 17050,  47412,  83079, ..., 842384, 871142, 899492],
       [  6393,  35253,  52308, ..., 859342, 873444, 895657]])

In [34]:
indices_seq_b=np.sort(epoch_indices_seq)

In [35]:
indices_seq_b=indices_seq_b.reshape(-1,indices_seq_b.shape[-1])

In [36]:
b1=indices_b[0]

In [37]:
b1

array([ 24942, 183749, 191654, 224871, 298738, 336289, 342869, 345013,
       385514, 456134, 503203, 510087, 526842, 536261, 557570, 586616,
       618544, 623743, 659386, 677357, 713894, 734069, 745322, 747838,
       753991, 766285, 776865, 785565, 812722, 863796, 877826, 879274])

In [39]:
b1==indices_b

array([[ True,  True,  True, ...,  True,  True,  True],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [43]:
np.where(np.all(b1==indices_b,axis=1))

(array([0]),)

In [38]:
len(np.where(np.all(b1==indices_b,axis=1))[0])

1

In [51]:
for bidx in range(indices_b.shape[0]):
    cb=indices_b[bidx]
    l=len(np.where(np.all(cb==indices_b,axis=1))[0])
    if l!=1:
        print("AHA at bidx {} l is {}".format(bidx,l))
    if bidx%10000==0:
        print("bidx now: {}".format(bidx))

bidx now: 0
bidx now: 10000
bidx now: 20000
bidx now: 30000
bidx now: 40000
bidx now: 50000
bidx now: 60000
bidx now: 70000
bidx now: 80000
bidx now: 90000
bidx now: 100000
bidx now: 110000
bidx now: 120000
bidx now: 130000
bidx now: 140000
bidx now: 150000
bidx now: 160000
bidx now: 170000
bidx now: 180000
bidx now: 190000
bidx now: 200000
bidx now: 210000
bidx now: 220000


In [50]:
for bidx in range(indices_seq_b.shape[0]):
    cb=indices_seq_b[bidx]
    l=len(np.where(np.all(cb==indices_seq_b,axis=1))[0])
    if l!=10:
        print("AHA at bidx {} l is {}".format(bidx,l))
    if bidx%10000==0:
        print("bidx now: {}".format(bidx))

bidx now: 0
bidx now: 10000
bidx now: 20000
bidx now: 30000
bidx now: 40000
bidx now: 50000
bidx now: 60000
bidx now: 70000
bidx now: 80000
bidx now: 90000
bidx now: 100000
bidx now: 110000
bidx now: 120000
bidx now: 130000
bidx now: 140000
bidx now: 160000
bidx now: 170000
bidx now: 180000
bidx now: 190000
bidx now: 200000
bidx now: 210000
bidx now: 220000


In [36]:
for b in range(three_epoch_indices.shape[1])
    indices_b[:,b,:]=np.sort(three_epoch_indices[:,b,:])
    print(indices_b)

[[  7346  38463  45971  56189  75114 110135 116755 119428 188582 251946
  283839 385697 397195 399842 443184 457836 476550 533139 535616 583882
  660921 679130 685455 693171 693523 709217 786646 794527 807083 847274
  852979 857119]
 [ 59298  66214 121634 133316 141612 163655 183574 183859 184010 187351
  225817 253146 279869 288095 297289 298148 368546 451687 507385 511835
  534216 588945 625061 648240 658682 689015 724455 771314 824120 836799
  846016 855052]
 [ 34568  51123 107609 139357 145233 191560 234186 238041 276236 284807
  313682 343451 362712 391716 444595 455551 459019 482891 490635 515218
  581666 589091 639723 649514 655404 676805 719022 744788 771892 857820
  871679 874750]]
[[ 50360  58232  69307  95613 158429 185669 246366 255080 267561 289207
  297880 332420 339781 345801 357788 375146 436349 475136 504511 522725
  552972 578028 612659 639057 650189 692776 696980 778828 792003 802151
  825558 865717]
 [ 32413  55045 101540 112003 148912 167584 204846 250301 278529 29

In [34]:
[x in dset.train_indices for x in three_epoch_indices[2,20000]]

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]